
const state={manifest:null,course:null,checklists:null,incidents:null,publicationLab:null,publishBuilder:null,finalProject:null,progress:{completedLessons:[],checklistItems:[],quizScores:{},publicationReports:[],publishBuilds:[],finalReports:[]}};
const $=s=>document.querySelector(s);
async function loadJson(p){const r=await fetch(p);if(!r.ok)throw Error("No se pudo cargar "+p);return r.json()}
function save(){localStorage.setItem(state.manifest.progressKey,JSON.stringify(state.progress))}
function load(){const r=localStorage.getItem(state.manifest.progressKey);if(r)try{state.progress={...state.progress,...JSON.parse(r)}}catch{}}
function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function dl(n,t,type="text/plain;charset=utf-8"){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
function nav(){return `<nav class="top-nav"><a href="#/">Inicio</a><a href="#/modules">Módulos</a><a href="#/publication-lab">Laboratorio</a><a href="#/publish-builder">Constructor</a><a href="#/final-project">Proyecto final</a><a href="#/publication-errors">Errores</a><a href="#/certificate">Constancia</a></nav>`}
function render(c){$("#app").innerHTML=c}
function lessons(){return state.course.modules.flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id})))}
function home(){render(`${nav()}<section class="hero"><p class="eyebrow">${state.manifest.route} · ${state.manifest.category}</p><h1>${state.manifest.title}</h1><p>${state.manifest.description}</p><div class="hero-actions"><a class="button primary" href="#/modules">Empezar curso</a><a class="button" href="#/publication-lab">Laboratorio</a><a class="button" href="#/final-project">Proyecto final</a></div></section><section class="grid stats"><article><strong>${state.course.modules.length}</strong><span>Módulos</span></article><article><strong>${lessons().length}</strong><span>Lecciones</span></article><article><strong>${state.publishBuilder.templates.length}</strong><span>Plantillas</span></article><article><strong>${state.finalProject.steps.length}</strong><span>Pasos finales</span></article></section>`)}
function modules(){render(`${nav()}<main><h1>Módulos</h1><div class="grid cards">${state.course.modules.map(m=>`<article class="card"><div class="badge">${m.icon}</div><h2>${m.title}</h2><p>${m.description}</p><a class="button" href="#/module/${m.id}">Ver módulo</a></article>`).join("")}</div></main>`)}
function module(id){const m=state.course.modules.find(x=>x.id===id);if(!m)return nf();render(`${nav()}<main><a href="#/modules">← Volver</a><h1>${m.title}</h1><p>${m.description}</p><section class="list">${m.lessons.map(l=>`<a class="list-item" href="#/lesson/${m.id}/${l.id}"><span>${state.progress.completedLessons.includes(l.id)?"✅":"○"}</span><strong>${l.title}</strong></a>`).join("")}</section><a class="button primary" href="#/quiz/${m.id}">Realizar quiz</a></main>`)}
function lesson(mid,lid){const m=state.course.modules.find(x=>x.id===mid),l=m?.lessons.find(x=>x.id===lid);if(!l)return nf();render(`${nav()}<main class="lesson"><a href="#/module/${mid}">← Volver</a><h1>${l.title}</h1><div class="panel"><h2>Idea clave</h2><p>${l.keyIdea}</p><h2>Teoría breve</h2><p>${l.shortTheory}</p><h2>Ejemplo práctico</h2><p>${l.practicalExample}</p><h2>Error común</h2><p>${l.commonMistake}</p><h2>Qué hacer ahora</h2><p>${l.whatToDoNow}</p><h2>Alerta</h2><p>${l.alert}</p><h2>Conceptos clave</h2><ul>${l.keyPoints.map(p=>`<li>${p}</li>`).join("")}</ul></div><button class="button primary" onclick="markLesson('${lid}')">Marcar como completada</button></main>`)}
window.markLesson=id=>{if(!state.progress.completedLessons.includes(id))state.progress.completedLessons.push(id);save();history.back()}
function quiz(mid){const m=state.course.modules.find(x=>x.id===mid);if(!m)return nf();render(`${nav()}<main><h1>Quiz: ${m.title}</h1><form id="quizForm" class="panel">${m.quiz.map((q,i)=>`<fieldset><legend>${i+1}. ${q.question}</legend>${q.options.map((op,j)=>`<label><input type="radio" name="${q.id}" value="${j}"> ${op}</label>`).join("")}</fieldset>`).join("")}<button class="button primary">Guardar resultado</button></form><div id="quizResult"></div></main>`);$("#quizForm").onsubmit=e=>{e.preventDefault();let sc=0;m.quiz.forEach(q=>{const s=document.querySelector(`input[name="${q.id}"]:checked`);if(s&&+s.value===q.correctAnswerIndex)sc++});state.progress.quizScores[mid]={score:sc,total:m.quiz.length,date:new Date().toISOString()};save();$("#quizResult").innerHTML=`<div class="success">Resultado: ${sc}/${m.quiz.length}</div>`}}
function publicationLab(){render(`${nav()}<main><h1>Laboratorio de publicación simulada</h1><div class="grid cards">${state.publicationLab.platforms.map(p=>`<article class="card"><h2>${p.name}</h2><p>${p.bestFor}</p><p><strong>Puntaje:</strong> ${p.recommendationScore}/10</p><a class="button" href="#/platform/${p.id}">Ver flujo</a></article>`).join("")}</div><section class="panel"><h2>Checklist general</h2>${state.publicationLab.publicationChecklist.map(i=>`<label class="check-row"><input type="checkbox"> ${i.text}</label>`).join("")}</section></main>`)}
function platform(id){const p=state.publicationLab.platforms.find(x=>x.id===id);if(!p)return nf();const report=`Reporte de publicación simulada\n\nPlataforma: ${p.name}\nRecomendado para: ${p.bestFor}\n\nRequisitos:\n${p.requirements.map(x=>"- "+x).join("\n")}\n\nPasos:\n${p.steps.map((x,i)=>`${i+1}. ${x}`).join("\n")}\n`;render(`${nav()}<main><a href="#/publication-lab">← Volver</a><h1>${p.name}</h1><p>${p.bestFor}</p><section class="panel"><h2>Flujo guiado</h2><ol>${p.steps.map(x=>`<li>${x}</li>`).join("")}</ol></section><section class="panel"><h2>Reporte</h2><pre>${esc(report)}</pre><button class="button" onclick="dl('${p.id}-reporte.txt', \`${esc(report)}\`)">Descargar .txt</button></section></main>`)}
function publicationErrors(){render(`${nav()}<main><h1>Errores frecuentes</h1><div class="grid cards">${state.publicationLab.errorScenarios.map(e=>`<article class="card"><span class="pill">${e.platform}</span><h2>${e.title}</h2><p><strong>Síntoma:</strong> ${e.symptom}</p><p><strong>Causa probable:</strong> ${e.likelyCause}</p><ol>${e.fixSteps.map(s=>`<li>${s}</li>`).join("")}</ol></article>`).join("")}</div></main>`)}
function publishBuilder(){render(`${nav()}<main><h1>Constructor de proyecto publicable</h1><div class="grid cards">${state.publishBuilder.templates.map(t=>`<article class="card"><h2>${t.title}</h2><p>${t.description}</p><p><strong>Plataforma sugerida:</strong> ${t.recommendedPlatform}</p><a class="button" href="#/publish-template/${t.id}">Construir</a></article>`).join("")}</div></main>`)}
function generateLanding(d){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(d.siteTitle)}</title><style>body{margin:0;font-family:Arial,sans-serif;background:#0f172a;color:#f8fafc;line-height:1.6}header,section,footer{width:min(960px,calc(100% - 32px));margin:auto;padding:48px 0}.hero{min-height:60vh;display:grid;place-items:center;text-align:center}h1{font-size:clamp(2rem,5vw,4rem);line-height:1.05}.btn{display:inline-block;background:#38bdf8;color:#071018;padding:12px 18px;border-radius:12px;text-decoration:none;font-weight:700}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card{background:#1e293b;border:1px solid #334155;border-radius:18px;padding:20px}</style></head><body><header class="hero"><div><h1>${esc(d.heroTitle)}</h1><p>${esc(d.heroText)}</p><a class="btn" href="${esc(d.ctaLink)}">${esc(d.ctaText)}</a></div></header><section id="proyectos"><h2>${esc(d.sectionTitle)}</h2><div class="cards"><article class="card"><h3>Proyecto 1</h3><p>Descripción breve.</p></article><article class="card"><h3>Proyecto 2</h3><p>Descripción breve.</p></article><article class="card"><h3>Proyecto 3</h3><p>Descripción breve.</p></article></div></section><footer id="contacto"><p>${esc(d.contactText)}</p></footer></body></html>`}
function publishTemplate(id){const t=state.publishBuilder.templates.find(x=>x.id===id);if(!t)return nf();render(`${nav()}<main><a href="#/publish-builder">← Volver</a><h1>${t.title}</h1><form id="form" class="panel">${t.fields.map(f=>`<label>${f.label}<input class="builder-input" name="${f.id}" value="${esc(f.default)}"></label>`).join("")}<button class="button primary">Generar proyecto</button></form><section class="panel"><textarea id="out"></textarea><button class="button" id="htmlBtn">Descargar index.html</button><button class="button" id="reportBtn">Descargar reporte .txt</button></section></main>`);const data=()=>Object.fromEntries(new FormData($("#form")).entries());const update=()=>{$("#out").value=generateLanding(data())};$("#form").onsubmit=e=>{e.preventDefault();update();state.progress.publishBuilds.unshift({template:t.title,date:new Date().toISOString()});save()};$("#htmlBtn").onclick=()=>dl("index.html",generateLanding(data()),"text/html;charset=utf-8");$("#reportBtn").onclick=()=>dl("reporte-publicacion.txt",`Plantilla: ${t.title}\nPlataforma sugerida: ${t.recommendedPlatform}\nChecklist:\n${state.publishBuilder.deployChecklist.map(i=>"- "+i.text).join("\n")}`);update()}
function finalProject(){render(`${nav()}<main><h1>${state.finalProject.title}</h1><p>${state.finalProject.description}</p><div class="hero-actions"><a class="button primary" href="#/final-report-builder">Generar reporte final</a><a class="button" href="#/deploy-outcomes">Simular deploy</a><a class="button" href="#/final-troubleshooting">Resolver errores</a></div><section class="grid cards">${state.finalProject.steps.map((s,i)=>`<article class="card"><span class="pill">Paso ${i+1}</span><h2>${s.title}</h2><p>${s.goal}</p><ul>${s.tasks.map(t=>`<li>${t}</li>`).join("")}</ul><p class="success">${s.checkpoint}</p><p class="note"><strong>Riesgo:</strong> ${s.risk}</p></article>`).join("")}</section><section class="panel"><h2>Checklist final</h2>${state.finalProject.finalChecklist.map(i=>`<label class="check-row"><input type="checkbox"> ${i.text}</label>`).join("")}</section></main>`)}
function finalReportBuilder(){render(`${nav()}<main><a href="#/final-project">← Volver</a><h1>Reporte final de publicación</h1><form id="form" class="panel">${state.finalProject.builderFields.map(f=>`<label>${f.label}<input class="builder-input" name="${f.id}" value="${esc(f.default)}"></label>`).join("")}<button class="button primary">Generar reporte</button></form><section class="panel"><textarea id="out"></textarea><button class="button" id="download">Descargar reporte .txt</button></section></main>`);const gen=()=>{const d=Object.fromEntries(new FormData($("#form")).entries());return `Reporte final de publicación\n\nProyecto: ${d.projectName}\nTipo: ${d.projectType}\nPlataforma: ${d.chosenPlatform}\nEstado local: ${d.localStatus}\nURL pública o simulada: ${d.publicUrl}\nRiesgo principal: ${d.mainIssue}\nPróxima mejora: ${d.nextImprovement}\n\nChecklist final:\n${state.finalProject.finalChecklist.map(i=>"- "+i.text).join("\n")}\n`};$("#form").onsubmit=e=>{e.preventDefault();$("#out").value=gen();state.progress.finalReports.unshift({date:new Date().toISOString()});save()};$("#download").onclick=()=>dl("reporte-final-publicacion.txt",$("#out").value||gen());$("#out").value=gen()}
function deployOutcomes(){render(`${nav()}<main><h1>Simulación de deploy</h1><div class="grid cards">${state.finalProject.deployOutcomes.map(o=>`<article class="card"><span class="pill">${o.status}</span><h2>${o.title}</h2><pre>${esc(o.terminal)}</pre><p>${o.meaning}</p></article>`).join("")}</div></main>`)}
function finalTroubleshooting(){render(`${nav()}<main><h1>Solución de errores</h1><div class="grid cards">${state.finalProject.troubleshooting.map(t=>`<article class="card"><h2>${t.problem}</h2><p><strong>Diagnóstico:</strong> ${t.diagnosis}</p><p><strong>Solución:</strong> ${t.solution}</p></article>`).join("")}</div></main>`)}
function checklists(){render(`${nav()}<main><h1>Checklists</h1><div class="grid cards">${state.checklists.checklists.map(c=>`<article class="card"><h2>${c.title}</h2><p>${c.description}</p><a class="button" href="#/checklist/${c.id}">Abrir</a></article>`).join("")}</div></main>`)}
function checklist(id){const c=state.checklists.checklists.find(x=>x.id===id);if(!c)return nf();render(`${nav()}<main><a href="#/checklists">← Volver</a><h1>${c.title}</h1><div class="panel">${c.items.map(i=>`<label class="check-row"><input type="checkbox" ${state.progress.checklistItems.includes(i.id)?"checked":""} onchange="toggleChecklist('${i.id}')"> ${i.text}</label>`).join("")}</div></main>`)}
window.toggleChecklist=id=>{const a=state.progress.checklistItems,i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);save()}
function cases(){render(`${nav()}<main><h1>Casos prácticos</h1><div class="grid cards">${state.incidents.incidents.map(i=>`<article class="card"><span class="pill">${i.severity}</span><h2>${i.title}</h2><p>${i.objective}</p><a class="button" href="#/case/${i.id}">Resolver</a></article>`).join("")}</div></main>`)}
function caseView(id){const i=state.incidents.incidents.find(x=>x.id===id);if(!i)return nf();render(`${nav()}<main><a href="#/cases">← Volver</a><h1>${i.title}</h1><section class="panel"><h2>Pasos</h2><ol>${i.steps.map(s=>`<li>${s}</li>`).join("")}</ol><p class="success">${i.guidedDecision.feedback}</p></section></main>`)}
function certificate(){render(`${nav()}<main><h1>Constancia interna</h1><div class="certificate"><h2>${state.manifest.title}</h2><p>Lecciones completadas: ${state.progress.completedLessons.length}/${lessons().length}</p><p>Proyectos generados: ${(state.progress.publishBuilds||[]).length}</p><p>Reportes finales: ${(state.progress.finalReports||[]).length}</p><p class="note">Constancia orientativa, no oficial.</p><button class="button" onclick="window.print()">Imprimir o guardar PDF</button></div></main>`)}
function nf(){render(`${nav()}<main><h1>No encontrado</h1></main>`)}
function router(){const [r,a,b]=location.hash.replace(/^#\/?/,"").split("/").filter(Boolean);if(!r)return home();({modules,module,lesson,quiz,"publication-lab":publicationLab,platform,"publication-errors":publicationErrors,"publish-builder":publishBuilder,"publish-template":publishTemplate,"final-project":finalProject,"final-report-builder":finalReportBuilder,"deploy-outcomes":deployOutcomes,"final-troubleshooting":finalTroubleshooting,checklists,checklist,cases,case:caseView,certificate}[r]||nf)(a,b)}
async function init(){state.manifest=await loadJson("src/data/course_manifest.json");state.course=await loadJson(state.manifest.dataPaths.course);state.checklists=await loadJson(state.manifest.dataPaths.checklists);state.incidents=await loadJson(state.manifest.dataPaths.incidents);state.publicationLab=await loadJson(state.manifest.dataPaths.publicationLab);state.publishBuilder=await loadJson(state.manifest.dataPaths.publishBuilder);state.finalProject=await loadJson(state.manifest.dataPaths.finalPublishProject);load();addEventListener("hashchange",router);router();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.warn)}
init().catch(e=>document.body.innerHTML=`<main class="error"><h1>Error</h1><pre>${e.message}</pre></main>`);
