
const state={manifest:null,course:null,checklists:null,incidents:null,gitLab:null,repoBuilder:null,githubProject:null,progress:{completedLessons:[],checklistItems:[],quizScores:{},gitPractices:[],repoBuilds:[],githubProjects:[]}};
const $=s=>document.querySelector(s);
async function loadJson(p){const r=await fetch(p);if(!r.ok)throw Error("No se pudo cargar "+p);return r.json()}
function save(){localStorage.setItem(state.manifest.progressKey,JSON.stringify(state.progress))}
function load(){const r=localStorage.getItem(state.manifest.progressKey);if(r)try{state.progress={...state.progress,...JSON.parse(r)}}catch{}}
function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function dl(n,t,type="text/plain;charset=utf-8"){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
function nav(){return `<nav class="top-nav"><a href="#/">Inicio</a><a href="#/modules">Módulos</a><a href="#/git-lab">Laboratorio Git</a><a href="#/repo-builder">README/.gitignore</a><a href="#/github-project">Proyecto GitHub</a><a href="#/commands">Comandos</a><a href="#/certificate">Constancia</a></nav>`}
function render(c){$("#app").innerHTML=c}
function lessons(){return state.course.modules.flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id})))}
function home(){render(`${nav()}<section class="hero"><p class="eyebrow">${state.manifest.route} · ${state.manifest.category}</p><h1>${state.manifest.title}</h1><p>${state.manifest.description}</p><div class="hero-actions"><a class="button primary" href="#/modules">Empezar curso</a><a class="button" href="#/git-lab">Laboratorio Git</a><a class="button" href="#/github-project">Proyecto guiado GitHub</a></div></section><section class="grid stats"><article><strong>${state.course.modules.length}</strong><span>Módulos</span></article><article><strong>${lessons().length}</strong><span>Lecciones</span></article><article><strong>${state.gitLab.scenarios.length}</strong><span>Escenarios Git</span></article><article><strong>${state.githubProject.steps.length}</strong><span>Pasos GitHub</span></article></section>`)}
function modules(){render(`${nav()}<main><h1>Módulos</h1><div class="grid cards">${state.course.modules.map(m=>`<article class="card"><h2>${m.title}</h2><p>${m.description}</p><a class="button" href="#/module/${m.id}">Ver módulo</a></article>`).join("")}</div></main>`)}
function module(id){const m=state.course.modules.find(x=>x.id===id);if(!m)return nf();render(`${nav()}<main><a href="#/modules">← Volver</a><h1>${m.title}</h1><p>${m.description}</p><section class="list">${m.lessons.map(l=>`<a class="list-item" href="#/lesson/${m.id}/${l.id}"><span>${state.progress.completedLessons.includes(l.id)?"✅":"○"}</span><strong>${l.title}</strong></a>`).join("")}</section><a class="button primary" href="#/quiz/${m.id}">Realizar quiz</a></main>`)}
function lesson(mid,lid){const m=state.course.modules.find(x=>x.id===mid),l=m?.lessons.find(x=>x.id===lid);if(!l)return nf();render(`${nav()}<main class="lesson"><a href="#/module/${mid}">← Volver</a><h1>${l.title}</h1><div class="panel"><h2>Idea clave</h2><p>${l.keyIdea}</p><h2>Teoría breve</h2><p>${l.shortTheory}</p><h2>Ejemplo práctico</h2><p>${l.practicalExample}</p><h2>Error común</h2><p>${l.commonMistake}</p><h2>Qué hacer ahora</h2><p>${l.whatToDoNow}</p><h2>Conceptos clave</h2><ul>${l.keyPoints.map(p=>`<li>${p}</li>`).join("")}</ul></div><button class="button primary" onclick="markLesson('${lid}')">Marcar como completada</button></main>`)}
window.markLesson=id=>{if(!state.progress.completedLessons.includes(id))state.progress.completedLessons.push(id);save();history.back()}
function quiz(mid){const m=state.course.modules.find(x=>x.id===mid);if(!m)return nf();render(`${nav()}<main><h1>Quiz: ${m.title}</h1><form id="quizForm" class="panel">${m.quiz.map((q,i)=>`<fieldset><legend>${i+1}. ${q.question}</legend>${q.options.map((op,j)=>`<label><input type="radio" name="${q.id}" value="${j}"> ${op}</label>`).join("")}</fieldset>`).join("")}<button class="button primary">Guardar resultado</button></form><div id="quizResult"></div></main>`);$("#quizForm").onsubmit=e=>{e.preventDefault();let sc=0;m.quiz.forEach(q=>{const s=document.querySelector(`input[name="${q.id}"]:checked`);if(s&&+s.value===q.correctAnswerIndex)sc++});state.progress.quizScores[mid]={score:sc,total:m.quiz.length,date:new Date().toISOString()};save();$("#quizResult").innerHTML=`<div class="success">Resultado: ${sc}/${m.quiz.length}</div>`}}
function gitLab(){render(`${nav()}<main><h1>Laboratorio Git simulado</h1><div class="grid cards">${state.gitLab.scenarios.map(s=>`<article class="card"><span class="pill">${s.difficulty}</span><h2>${s.title}</h2><p>${s.context}</p><a class="button" href="#/git-scenario/${s.id}">Practicar</a></article>`).join("")}</div></main>`)}
function scenario(id){const s=state.gitLab.scenarios.find(x=>x.id===id);if(!s)return nf();const rep=`Reporte de práctica Git\n\nEscenario: ${s.title}\nObjetivo: ${s.objective}\nComando recomendado:\n${s.correctCommand}\n\nError evitado:\n${s.whyWrong}\n\nPróximo paso:\n${s.reportHint}\n`;render(`${nav()}<main><a href="#/git-lab">← Volver</a><h1>${s.title}</h1><p><strong>Contexto:</strong> ${s.context}</p><section class="panel"><h2>Estado simulado</h2><pre>${esc(s.simulatedStatus)}</pre></section><section class="panel"><h2>Flujo guiado</h2><ol>${s.steps.map(st=>`<li><code>${esc(st.command)}</code><p>${st.explanation}</p></li>`).join("")}</ol></section><div class="grid cards"><article class="card"><h2>Correcto</h2><pre>${esc(s.correctCommand)}</pre></article><article class="card"><h2>Error común</h2><pre>${esc(s.wrongCommand)}</pre><p>${s.whyWrong}</p></article></div><section class="panel"><h2>Reporte</h2><pre>${esc(rep)}</pre><button class="button" onclick="dl('${s.id}-reporte-git.txt', \`${esc(rep)}\`)">Descargar reporte</button></section></main>`)}
function commands(){render(`${nav()}<main><h1>Comandos esenciales</h1><div class="grid cards">${state.gitLab.commands.map(c=>`<article class="card"><h2><code>${c.command}</code></h2><p>${c.purpose}</p><p><strong>Cuándo usar:</strong> ${c.whenToUse}</p><pre>${esc(c.example)}</pre><p class="note"><strong>Error común:</strong> ${c.commonMistake}</p></article>`).join("")}</div></main>`)}
function repoBuilder(){render(`${nav()}<main><h1>Constructor de README y .gitignore</h1><div class="grid cards"><article class="card"><h2>README.md</h2><a class="button" href="#/readme-builder">Generar README</a></article><article class="card"><h2>.gitignore</h2><a class="button" href="#/gitignore-builder">Generar .gitignore</a></article><article class="card"><h2>Mensajes de commit</h2><a class="button" href="#/commit-templates">Ver plantillas</a></article><article class="card"><h2>Repositorio limpio</h2><a class="button" href="#/repo-checklist">Checklist</a></article></div></main>`)}
function readmeBuilder(){renderList("readme")}
function gitignoreBuilder(){renderList("gitignore")}
function renderList(type){const arr=type==="readme"?state.repoBuilder.readmeTemplates:state.repoBuilder.gitignoreTemplates;render(`${nav()}<main><a href="#/repo-builder">← Volver</a><h1>${type==="readme"?"Generador README":"Generador .gitignore"}</h1><div class="grid cards">${arr.map(t=>`<article class="card"><h2>${t.title}</h2><p>${t.description}</p><a class="button" href="#/${type}-template/${t.id}">Usar</a></article>`).join("")}</div></main>`)}
function readmeTemplate(id){const t=state.repoBuilder.readmeTemplates.find(x=>x.id===id);if(!t)return nf();render(`${nav()}<main><a href="#/readme-builder">← Volver</a><h1>${t.title}</h1><form id="form" class="panel">${t.fields.map(f=>`<label>${f.label}<input class="builder-input" name="${f.id}" value="${esc(f.default)}"></label>`).join("")}<button class="button primary">Generar README</button></form><section class="panel"><textarea id="out"></textarea><button class="button" id="download">Descargar README.md</button></section></main>`);const gen=()=>{const d=Object.fromEntries(new FormData($("#form")).entries());return `# ${d.projectTitle}\n\n## Descripción\n\n${d.description}\n\n## Tecnologías usadas\n\n${d.technologies}\n\n## Cómo probar\n\n${d.howToRun}\n\n## Estado actual\n\n${d.status}\n\n## Próximas mejoras\n\n${d.nextSteps}\n`};$("#form").onsubmit=e=>{e.preventDefault();$("#out").value=gen();saveBuild(t.title)};$("#download").onclick=()=>dl("README.md",$("#out").value||gen());$("#out").value=gen()}
function gitignoreTemplate(id){const t=state.repoBuilder.gitignoreTemplates.find(x=>x.id===id);if(!t)return nf();const txt=t.entries.join("\n")+"\n";render(`${nav()}<main><a href="#/gitignore-builder">← Volver</a><h1>${t.title}</h1><p>${t.description}</p><section class="panel"><textarea id="out">${esc(txt)}</textarea><button class="button" onclick="dl('.gitignore',$('#out').value)">Descargar .gitignore</button></section></main>`)}
function saveBuild(title){state.progress.repoBuilds.unshift({title,date:new Date().toISOString()});state.progress.repoBuilds=state.progress.repoBuilds.slice(0,20);save()}
function commitTemplates(){render(`${nav()}<main><h1>Plantillas de commit</h1><div class="grid cards">${state.repoBuilder.commitTemplates.map(c=>`<article class="card"><h2>${c.title}</h2><pre>${esc(c.message)}</pre></article>`).join("")}</div></main>`)}
function repoChecklist(){render(`${nav()}<main><h1>Checklist de repositorio limpio</h1><section class="panel">${state.repoBuilder.repoChecklist.map(i=>`<label class="check-row"><input type="checkbox"> ${i.text}</label>`).join("")}</section></main>`)}
function githubProject(){render(`${nav()}<main><h1>${state.githubProject.title}</h1><p>${state.githubProject.description}</p><div class="hero-actions"><a class="button primary" href="#/github-builder">Generar recursos del proyecto</a><a class="button" href="#/push-simulation">Ver simulación push</a><a class="button" href="#/github-mistakes">Errores comunes</a></div><section class="grid cards">${state.githubProject.steps.map((s,i)=>`<article class="card"><span class="pill">Paso ${i+1}</span><h2>${s.title}</h2><p>${s.goal}</p><ul>${s.tasks.map(t=>`<li>${t}</li>`).join("")}</ul><pre>${esc(s.command)}</pre><p class="success">${s.checkpoint}</p></article>`).join("")}</section><section class="panel"><h2>Checklist final</h2>${state.githubProject.finalChecklist.map(i=>`<label class="check-row"><input type="checkbox"> ${i.text}</label>`).join("")}</section></main>`)}
function githubBuilder(){render(`${nav()}<main><a href="#/github-project">← Volver</a><h1>Generador del proyecto GitHub</h1><form id="form" class="panel">${state.githubProject.builderFields.map(f=>`<label>${f.label}<input class="builder-input" name="${f.id}" value="${esc(f.default)}"></label>`).join("")}<button class="button primary">Generar reporte</button></form><section class="panel"><textarea id="out"></textarea><button class="button" id="download">Descargar reporte .txt</button><button class="button" id="downloadReadme">Descargar README.md</button></section></main>`);const gen=()=>{const d=Object.fromEntries(new FormData($("#form")).entries());return `Proyecto GitHub\n\nTítulo: ${d.projectTitle}\nDescripción: ${d.description}\nRepositorio sugerido: ${d.repoName}\nTecnologías: ${d.technologies}\nCómo probar: ${d.runInstructions}\nPróximas mejoras: ${d.nextSteps}\n\nComandos sugeridos:\ngit init\ngit status\ngit add .\ngit commit -m "Crear versión inicial del proyecto web"\ngit remote add origin URL_DEL_REPOSITORIO\ngit push -u origin main\n`};const readme=()=>{const d=Object.fromEntries(new FormData($("#form")).entries());return `# ${d.projectTitle}\n\n## Descripción\n\n${d.description}\n\n## Tecnologías\n\n${d.technologies}\n\n## Cómo probar\n\n${d.runInstructions}\n\n## Próximas mejoras\n\n${d.nextSteps}\n`};$("#form").onsubmit=e=>{e.preventDefault();$("#out").value=gen();state.progress.githubProjects.unshift({title:"Proyecto GitHub",date:new Date().toISOString()});save()};$("#download").onclick=()=>dl("reporte-proyecto-github.txt",$("#out").value||gen());$("#downloadReadme").onclick=()=>dl("README.md",readme());$("#out").value=gen()}
function pushSimulation(){render(`${nav()}<main><h1>Simulación de push</h1><div class="grid cards">${state.githubProject.pushSimulation.map(p=>`<article class="card"><h2>${p.title}</h2><pre>${esc(p.terminal)}</pre><p>${p.meaning}</p></article>`).join("")}</div></main>`)}
function githubMistakes(){render(`${nav()}<main><h1>Errores comunes al subir a GitHub</h1><div class="grid cards">${state.githubProject.commonMistakes.map(m=>`<article class="card"><h2>${m.title}</h2><p><strong>Problema:</strong> ${m.problem}</p><p><strong>Solución:</strong> ${m.solution}</p></article>`).join("")}</div></main>`)}
function checklists(){render(`${nav()}<main><h1>Checklists</h1><div class="grid cards">${state.checklists.checklists.map(c=>`<article class="card"><h2>${c.title}</h2><p>${c.description}</p><a class="button" href="#/checklist/${c.id}">Abrir</a></article>`).join("")}</div></main>`)}
function checklist(id){const c=state.checklists.checklists.find(x=>x.id===id);if(!c)return nf();render(`${nav()}<main><a href="#/checklists">← Volver</a><h1>${c.title}</h1><div class="panel">${c.items.map(i=>`<label class="check-row"><input type="checkbox" ${state.progress.checklistItems.includes(i.id)?"checked":""} onchange="toggleChecklist('${i.id}')"> ${i.text}</label>`).join("")}</div></main>`)}
window.toggleChecklist=id=>{const a=state.progress.checklistItems,i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);save()}
function certificate(){render(`${nav()}<main><h1>Constancia interna</h1><div class="certificate"><h2>${state.manifest.title}</h2><p>Lecciones: ${state.progress.completedLessons.length}/${lessons().length}</p><p>Prácticas Git: ${(state.progress.gitPractices||[]).length}</p><p>Recursos generados: ${(state.progress.repoBuilds||[]).length}</p><p>Proyectos guiados: ${(state.progress.githubProjects||[]).length}</p><p class="note">Constancia orientativa, no oficial.</p><button class="button" onclick="window.print()">Imprimir o guardar PDF</button></div></main>`)}
function nf(){render(`${nav()}<main><h1>No encontrado</h1></main>`)}
function router(){const [r,a,b]=location.hash.replace(/^#\/?/,"").split("/").filter(Boolean);if(!r)return home();({"modules":modules,module,lesson,quiz,"git-lab":gitLab,"git-scenario":scenario,commands,"repo-builder":repoBuilder,"readme-builder":readmeBuilder,"gitignore-builder":gitignoreBuilder,"readme-template":readmeTemplate,"gitignore-template":gitignoreTemplate,"commit-templates":commitTemplates,"repo-checklist":repoChecklist,"github-project":githubProject,"github-builder":githubBuilder,"push-simulation":pushSimulation,"github-mistakes":githubMistakes,checklists,checklist,certificate}[r]||nf)(a,b)}
async function init(){state.manifest=await loadJson("src/data/course_manifest.json");state.course=await loadJson(state.manifest.dataPaths.course);state.checklists=await loadJson(state.manifest.dataPaths.checklists);state.incidents=await loadJson(state.manifest.dataPaths.incidents);state.gitLab=await loadJson(state.manifest.dataPaths.gitLab);state.repoBuilder=await loadJson(state.manifest.dataPaths.repoBuilder);state.githubProject=await loadJson(state.manifest.dataPaths.githubProject);load();addEventListener("hashchange",router);router();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.warn)}
init().catch(e=>document.body.innerHTML=`<main class="error"><h1>Error</h1><pre>${e.message}</pre></main>`);
